<a href="https://colab.research.google.com/github/leilaamani/Machine-learning/blob/main/First_Numpy_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

In [6]:
a=np.zeros(10,dtype=np.int8)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [7]:
a=np.arange(10,50,dtype=np.int8)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49], dtype=int8)

In [8]:
A=np.ones((2,2),dtype=np.int8)
A

array([[1, 1],
       [1, 1]], dtype=int8)

In [9]:
B=np.ones((3,2),dtype=np.float16)
B

array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float16)

In [10]:
x=np.arange(10,dtype=np.float16)
y=np.ones_like(x)
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float16)

In [11]:
X=np.array([[1,2,3],[4,5,6]],dtype=np.int8)
Y=np.zeros_like(X)
print(X)
print(Y)

[[1 2 3]
 [4 5 6]]
[[0 0 0]
 [0 0 0]]


In [12]:
A=np.full((4,4),5,dtype=np.int8)
np.array([5]*16).reshape(4,4)


array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [13]:
X=np.array([[1,2,3],[4,5,6]],dtype=np.int8)
Y=np.full_like(X,7)
Y

array([[7, 7, 7],
       [7, 7, 7]], dtype=int8)

In [14]:
I=np.eye(3)
I=np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.random.randint(1,10,size=3)
np.random.randint(1,10,size=(3,3))

array([[5, 4, 4],
       [7, 8, 3],
       [3, 9, 2]])

In [16]:
np.random.random((3,3,3))
np.random.rand(3,3,3)

array([[[0.84807337, 0.47891814, 0.83285843],
        [0.67931717, 0.16343056, 0.64770767],
        [0.85494806, 0.68467388, 0.15225985]],

       [[0.24113367, 0.55547043, 0.49981916],
        [0.83799414, 0.94368419, 0.93923897],
        [0.8803061 , 0.20057301, 0.95506729]],

       [[0.60993906, 0.4924731 , 0.79587602],
        [0.05203683, 0.70715001, 0.19812976],
        [0.31850617, 0.62606613, 0.13793814]]])

In [17]:
x=np.array([1,2,5,7,9,3])
y=np.copy(x)
print(x,y)

[1 2 5 7 9 3] [1 2 5 7 9 3]


In [18]:
a=np.arange(1,11)
a[::-1]


array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [19]:
a=np.array([10,4,7,2])
np.sort(a)
np.argsort(a)

array([3, 1, 2, 0])

In [21]:
Z=np.arange(9,dtype=np.float64).reshape(3,3)
print(Z.dtype)
print(Z.size)
print(Z.itemsize)

float64
9
8


In [22]:
x=np.array([-2,9,-88,12])
x.astype(np.float16)

array([ -2.,   9., -88.,  12.], dtype=float16)

In [27]:
x=np.array([0,0,0,])
x.any()

False

In [24]:
x=np.array([-2,9,-88,12])
x.all()

True

In [30]:
A=np.arange(1,10).reshape(3,3)
A=np.tile(A,3)
A

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9, 7, 8, 9]])

In [31]:
A=np.arange(1,7).reshape(2,3)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
B=np.arange(7,13).reshape(2,3)
B

array([[ 7,  8,  9],
       [10, 11, 12]])

In [33]:
np.hstack((A,B))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [34]:
np.vstack((A,B))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [36]:
np.concatenate((A,B),0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [37]:
np.concatenate((A,B),1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])