<a href="https://colab.research.google.com/github/leilaamani/Machin-learning/blob/main/Numpy_Library_session02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
print(np.__version__)

1.21.6


In [ ]:
a=np.arange(1,17)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
A=np.arange(1,17).reshape(4,4)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
np.linspace(-1,1,10)

array([-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
        0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ])

In [ ]:
A=5*np.ones((4,5),dtype=np.int8)
A

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]], dtype=int8)

In [ ]:
A=np.full((4,5),5)
A

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [ ]:
I=np.eye(4)
I       

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.fliplr(I)

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]])

In [ ]:
A=np.arange(1,17).reshape(4,4)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
print(A.mean())      #total Avarege
print(A.mean(0))     #average of each column
print(A.mean(1))     #average of aech row

8.5
[ 7.  8.  9. 10.]
[ 2.5  6.5 10.5 14.5]


In [ ]:
print(A.var())      #total variance
print(A.var(0))     #variance of each column
print(A.var(1))     #variance of aech row

21.25
[20. 20. 20. 20.]
[1.25 1.25 1.25 1.25]


In [ ]:
print(A.std())      #total standard deviation
print(A.std(0))     #standard deviation of each column
print(A.std(1))     #standard deviation of aech row

4.6097722286464435
[4.47213595 4.47213595 4.47213595 4.47213595]
[1.11803399 1.11803399 1.11803399 1.11803399]


### **Transforming a row vector into a column vector in Numpy**

In [ ]:
a=np.array([1,2,3,4])
#a=a[...,None]
#a=a[:, np.newaxis]
a=a.reshape(-1,1)
a

array([[1],
       [2],
       [3],
       [4]])

# **Broadcasting**

In [3]:
A=np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
A[0]=10
A

array([[10, 10, 10],
       [ 4,  5,  6]])

In [9]:
A=np.array([[1,2,3],[4,5,6]])
A=A*10
A

array([[10, 20, 30],
       [40, 50, 60]])

In [10]:
A=np.array([[1,2,3],[4,5,6]])
A+=10
A

array([[11, 12, 13],
       [14, 15, 16]])

# **Boolean Array**

In [11]:
a=np.arange(1,17)
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [12]:
a>6

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [13]:
a[a>10]

array([11, 12, 13, 14, 15, 16])

In [14]:
a.mean()

8.5

In [15]:
a[a>a.mean()]

array([ 9, 10, 11, 12, 13, 14, 15, 16])

In [16]:
a[a<a.std()]

array([1, 2, 3, 4])

In [23]:
A=np.arange(1,17).reshape(4,4)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [26]:
A.mean()

8.5

In [27]:
A.std()

4.6097722286464435

In [29]:
A[(A>A.mean()) |(A<A.std())]

array([ 1,  2,  3,  4,  9, 10, 11, 12, 13, 14, 15, 16])

# **Random Vector**

In [34]:
np.random.random()

0.752204231563272

In [30]:
np.random.random(3)

array([0.33564756, 0.64284902, 0.2522136 ])

In [33]:
np.random.random((3,3))

array([[0.17602744, 0.04071199, 0.36250147],
       [0.12651334, 0.9917546 , 0.28733729],
       [0.24563712, 0.64038165, 0.10904584]])

In [35]:
np.random.seed(1)
np.random.rand(3,4)

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01],
       [3.96767474e-01, 5.38816734e-01, 4.19194514e-01, 6.85219500e-01]])

In [39]:
np.random.randint(3,20,size=(2,4))

array([[ 7, 14, 15, 19],
       [16, 12, 18,  3]])